const cities = [
    { value: "Ahmedabad" },
    { value: "Mumbai" },
    { value: "Delhi" },
    { value: "Bangalore" },
    { value: "Chennai" },
    { value: "Kolkata" },
    { value: "Hyderabad" },
    { value: "Pune" },
    { value: "Jaipur" },
    { value: "Surat" },
    { value: "Lucknow" },
    { value: "Kanpur" },
    { value: "Nagpur" },
    { value: "Visakhapatnam" },
    { value: "Indore" },
    { value: "Thane" },
    { value: "Bhopal" },
    { value: "Patna" },
    { value: "Vadodara" },
    { value: "Ghaziabad" },
    { value: "Ludhiana" },
    { value: "Agra" },
    { value: "Nashik" },
    { value: "Faridabad" },
    { value: "Meerut" },
    { value: "Rajkot" },
    { value: "Kalyan-Dombivli" },
    { value: "Vasai-Virar" },
    { value: "Varanasi" },
    { value: "Srinagar" }
  ];

export {cities};