const skills = [
    { "value": "JavaScript" },
    { "value": "Python" },
    { "value": "Java" },
    { "value": "C++" },
    { "value": "C#" },
    { "value": "Ruby" },
    { "value": "PHP" },
    { "value": "Swift" },
    { "value": "Objective-C" },
    { "value": "Kotlin" },
    { "value": "Go" },
    { "value": "R" },
    { "value": "SQL" },
    { "value": "NoSQL" },
    { "value": "HTML" },
    { "value": "CSS" },
    { "value": "Sass" },
    { "value": "LESS" },
    { "value": "TypeScript" },
    { "value": "React" },
    { "value": "Angular" },
    { "value": "Vue.js" },
    { "value": "Node.js" },
    { "value": "Express.js" },
    { "value": "Django" },
    { "value": "Flask" },
    { "value": "Ruby on Rails" },
    { "value": "Spring" },
    { "value": "Laravel" },
    { "value": "ASP.NET" },
    { "value": "Symfony" },
    { "value": "jQuery" },
    { "value": "Bootstrap" },
    { "value": "Tailwind CSS" },
    { "value": "Foundation" },
    { "value": "Backbone.js" },
    { "value": "Ember.js" },
    { "value": "Gatsby" },
    { "value": "Next.js" },
    { "value": "Nuxt.js" },
    { "value": "Redux" },
    { "value": "MobX" },
    { "value": "GraphQL" },
    { "value": "Apollo" },
    { "value": "RESTful APIs" },
    { "value": "SOAP" },
    { "value": "Microservices" },
    { "value": "Kubernetes" },
    { "value": "Docker" },
    { "value": "CI/CD" },
    { "value": "Jenkins" },
    { "value": "Travis CI" },
    { "value": "Git" },
    { "value": "GitHub" },
    { "value": "GitLab" },
    { "value": "Bitbucket" },
    { "value": "Agile" },
    { "value": "Scrum" },
    { "value": "Kanban" },
    { "value": "JIRA" },
    { "value": "Confluence" },
    { "value": "Trello" },
    { "value": "Asana" },
    { "value": "Project Management" },
    { "value": "Time Management" },
    { "value": "Communication" },
    { "value": "Team Collaboration" },
    { "value": "Problem Solving" },
    { "value": "Critical Thinking" },
    { "value": "Analytical Skills" },
    { "value": "Leadership" },
    { "value": "Public Speaking" },
    { "value": "Presentation Skills" },
    { "value": "Customer Service" },
    { "value": "Sales" },
    { "value": "Marketing" },
    { "value": "SEO" },
    { "value": "Content Marketing" },
    { "value": "Social Media Marketing" },
    { "value": "Email Marketing" },
    { "value": "Google Analytics" },
    { "value": "Adobe Photoshop" },
    { "value": "Adobe Illustrator" },
    { "value": "Adobe InDesign" },
    { "value": "Figma" },
    { "value": "Sketch" },
    { "value": "InVision" },
    { "value": "UX Design" },
    { "value": "UI Design" },
    { "value": "Wireframing" },
    { "value": "Prototyping" },
    { "value": "User Research" },
    { "value": "Usability Testing" },
    { "value": "Data Analysis" },
    { "value": "Machine Learning" },
    { "value": "Deep Learning" },
    { "value": "Artificial Intelligence" },
    { "value": "Data Visualization" },
    { "value": "Big Data" },
    { "value": "Hadoop" },
    { "value": "Spark" },
    { "value": "AWS" },
    { "value": "Azure" },
    { "value": "Google Cloud" }
]

export {skills}